apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-demo
  template:
    metadata:
      name: currency-demo-pod
      labels:
        app: currency-demo
    spec:
      containers:
      - name: currency-demo-container
        image: byckg3/currency-demo
        ports:
        - name: currency-port
          containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: currency-demo-svc
spec:
  selector:
    app: currency-demo
  ports:
  - port: 80
    targetPort: currency-port
