apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: currency-demo-svc
spec:
  type: NodePort
  selector:
    app: currency-demo
  ports:
  - name: http
    port: 80
    targetPort: demo-http-port