apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: currency-demo-deploy
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: currency-demo
  template:
    metadata:
      labels:
        app: currency-demo
    spec:
      securityContext:
        runAsNonRoot: true
        # runAsUser: 1000
      containers:
      - image: byckg3/currency-demo
        name: currency-demo-ctr
        ports:
        - name: demo-http-port
          containerPort: 8081
        terminationMessagePolicy: FallbackToLogsOnError
        readinessProbe:
          initialDelaySeconds: 20 # Defaults to 0 seconds. Minimum value is 0.
          periodSeconds: 5        # Default to 10 seconds. The minimum value is 1. 
          httpGet:
            path: /currencies
            port: demo-http-port
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /currencies
            port: demo-http-port
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "500m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: currency-demo-svc
# spec:
#   type: LoadBalancer
#   selector:
#     app: currency-demo
#   ports:
#   - port: 80
#     targetPort: demo-http-port